### ISSUE TITLE
Bug fight command

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#90]
(node:31686) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
Jul 10 22:23:01 Draftbot-1 node[31686]:     at FightCommand (/root/DraftBot-A-Discord-Adventure/src/commands/player/FightCommand.js:22:16)
Jul 10 22:23:01 Draftbot-1 node[31686]:     at async Function.launchCommand (/root/DraftBot-A-Discord-Adventure/src/core/Command.js:187:9)
Jul 10 22:23:01 Draftbot-1 node[31686]:     at async handleMessage (/root/DraftBot-A-Discord-Adventure/src/core/Command.js:97:7)
Jul 10 22:23:01 Draftbot-1 node[31686]:     at async Client.onDiscordMessage (/root/DraftBot-A-Discord-Adventure/index.js:70:7)
Jul 10 22:23:01 Draftbot-1 node[31686]: (node:31686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise wh$
Jul 10 22:23:01 Draftbot-1 node[31686]: (node:31686) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero ex$
Jul 10 22:33:08 Draftbot-1 systemd[1]: Stopping DiscordBot...
Jul 10 22:33:08 Draftbot-1 systemd[1]: Stopped DiscordBot.

**Comment by BastLast** [comment]
Plusieurs joueurs rapportent des problèmes avec les réactions. Peur être est-ce lié ?
https://discordapp.com/channels/429765017332613120/448055928105861120/731777076285276192
https://discordapp.com/channels/429765017332613120/448055928105861120/731851428624334900
